### PR TITLE
✨♻️ Add /industry pages

### LINKED ISSUE #1029: ⚠️ Urgent - new webpage - finance
Hi Brady,

Please action ASAP – the TV team need the webpage so they can start their testimonial video which will be embedded on the page.

1. Please create a new webpage in the style of [Education (ssw.com.au)](https://www.ssw.com.au/educational) with this content  [ Finance-industry-new-page.docx](https://sswcom.sharepoint.com/:w:/r/sites/SSWMarketing/Shared%20Documents/General/Seth%27s%20drafts/Finance-industry-new-page.docx?d=w8fdac88b1c7f4ec8ae1cf03086d6045c&csf=1&web=1&e=whUDom)
2. Put it in the ‘Who we work with’ section of the website
3. Make the URL ssw.com.au/industry/finance
4. Change the education page URL to /industry/education and move it into the ‘Who we work’ with section
5. Ask Seth if there are issues with organizing the content
6. Get it checked by Seth

@camillars @UlyssesMaclaren @Levijj22

### PR DESCRIPTION
**Pull request by bradystroud**
Add finance page

Fixes #1029

Affected routes:

- `/industry/finance`
- `/industry/educational`

Add done video, screenshots

### CODE REVIEW

**Review by Harry-Ross — CHANGES_REQUESTED** [review]
image

Now that you have made `prose-industry` in the Tailwind config, can you move these custom `<p>` and `<h3>` elements to there?

**Review by amankumarrr — APPROVED** [review]
LGTM

**Comment by bradystroud** [comment]
Feedback as per my conversation with @sethdailyssw 

- [x] Fix title to match the text
- [x] 'Finance Software Solutions' should be H1
- [x] 'Customised Technology Solutions' should be H2
- [x] 'Overview, How SSW can help, and How can SSW channel...' should be H3
- [x] Change Customised to Customized in the H2
- [x] photoshop the banner image to be SSW red (or close)
- [x] Add alt text to each image

**Review by Harry-Ross — APPROVED** [review]
lgtm 🍳

**Pull request merged**
