### PR TITLE
⚡Live Stream banner - Add static for upcoming UG

### LINKED ISSUE #3067: 🔍 SEO - Reduce Total Blocking Time
**Description**
Our SEO is down due to the TBL (see screenshot below).

**Screenshots**
Image
**Figure: TBL is high**

**Note**: Work done to improve live stream banner performance was done as part of this PBI with the misunderstanding that it would reduce total blocking time. A separate issue was created for this - see https://github.com/SSWConsulting/SSW.Website/issues/3108

### LINKED ISSUE #3108: ⚡LiveStream Banner - Add static fetching for live stream events
CC: @wicksipedia 

### Description

All pages on the site perform a client side fetch to check for upcoming livestream events. This increases the time taken for the banner to appear.

**Note**: I completed this in an attempt to improve our TBT (see 🔍 SEO - Reduce Total Blocking Time
), but as per my conversation with Aman this is unlikely to reduce TBT since the fetch is deferred. Creating this PBI to log the work.

### PR DESCRIPTION
**Pull request by Calinator444**
### Changes
- Added dynamic imports for all blocks component files
- moved common links on layout to _document.tsx to ensure they will only be loaded once
- Added static fetching for livestream events (In theory this should improve our performance when user groups are close
- Fixed broken image link in live stream banner
- Fixed Typo in `LiveSteam` component name

### Affected Routes
ssw.com.au/*

### Solved Issue
- Fixed #3108 
### Screenshots 

image
**Figure**: **Live stream banner tested on this branch**

<br>

https://github.com/SSWConsulting/SSW.People.Profiles/pull/1241

**Figure**: **About presenter now stretches fully if the presenter is not provided in the list**

### CODE REVIEW

**Comment by Calinator444** [comment]
😰 Please let this improve our performance

**Comment by Calinator444** [comment]
Todo - test the following before merging

- [x] Live stream banner event on page router template (including widget)
- [x] Live stream banner event on app router template (including widget)
- [x] Live stream banner event mocking on page router template (including widget)
- [x] Live stream banner event mocking on app router template (including widget)
- [x] CLS for all page router templates
- [x] CLS for all app router templates

**Comment by Calinator444** [comment]
For the record - @amankumarrr asked me to evaluate the changes made in this branch in staging. I am accountable for any bugs that may occur from merging this branch.

**Review by amankumarrr — APPROVED** [review]
LGTM - Assuming all the impacted areas are tested thoroughly

**Pull request merged**
