### PR TITLE
📄 Events - Clean Architecture Superpowers

### LINKED ISSUE #598: 📄 Events - Clean Architecture Superpowers
https://www.ssw.com.au/ssw/Events/Training/Clean-Architecture-Superpowers-Tour.aspx

As per my conversation with @camillars and @bradystroud , we think all SuperPower pages should be under the route of /events and Internship will remain under /training and remove all the content related to COVID on the page. 

```[tasklist]
### Tasks
- [ ] Tell Luke and Daniel to own the page
```

### PR DESCRIPTION
**Pull request by johnxu16**
Right after deployment:
- [x] Update menu.json https://github.com/SSWConsulting/SSW.Website.Menu.json/pull/90
- [x] Update frontdoor https://github.com/SSWConsulting/SSW.FrontDoor/pull/79

Fixes #598 

Affected routes:

- **/events/clean-architecture-superpowers-tour**
- /events/angular-superpowers-tour
- /events/azure-superpowers-tour

Add done video, screenshots

image
**Figure: EventHeading**

image
**Figure: Presenters**

image
**Figure: Content**

image
**Figure: Agenda**

### CODE REVIEW

**Review by Harry-Ross — APPROVED** [review]
LGTM 🚢

Very happy that the Lodash dependency conditional number functionality has been removed 🙂

**Comment by Harry-Ross** [comment]
Make sure to also change the other pages to use the index field after https://github.com/SSWConsulting/SSW.Website/pull/1129 gets merged in

**Comment by danielmackay** [comment]
The centred text looks weird.  I'm find with centred titles, but centred paragraphs doesn't look right.  Do you agree?

**Comment by danielmackay** [comment]
Images are broken: 
image

**Comment by danielmackay** [comment]
Can you switch the basics and the testing columns around? 
image

**Comment by danielmackay** [comment]
Is it just me or is that one MASSIVE ONION!?
image

**Comment by danielmackay** [comment]
Can you add nested bullets for these sub-points? 
image

**Review by danielmackay — CHANGES_REQUESTED** [review]
See comments on the PR.

**Comment by johnxu16** [comment]
> The centred text looks weird. I'm find with centred titles, but centred paragraphs doesn't look right. Do you agree?

@tiagov8 @hveraus

As per conversation with Aman, designers suggested we keep text centered in ContentCard.

It does look like a bit werid to me as well, so I temporaily switch off centered flag.

image
**Figure: Staging [website](https://app-sswwebsite-9eb3-pr-1133.azurewebsites.net)**

image
**Figure: Production [website](https://app-sswwebsite-9eb3-pr-1133.azurewebsites.net)**

1. What do we do with paragraph here?
A. Center
B. Left
C. Other

As per conversation with designers, we keep paragraph centered for consistency.

**Comment by johnxu16** [comment]
> Is it just me or is that one MASSIVE ONION!? image

Done - changed the MASSIVE onion to the md size.

Affected routes:
- /events/clean-architecture-workshop
- /events/clean-architecture-superpowers-tour

**Comment by johnxu16** [comment]
> Can you switch the basics and the testing columns around? image

Done - The change just been made on main branch.

**Comment by johnxu16** [comment]
> Images are broken: image

Done - added index number to clean-architecture-workshop.mdx | agenda

**Comment by johnxu16** [comment]
> Can you add nested bullets for these sub-points? image

Done - Added nested list style on `<VerticalListItem>` and Update document "clean-architecture-workshop"

image
**Figure: [https://app-sswwebsite-9eb3-pr-1133.azurewebsites.net/events/clean-architecture-workshop](https://app-sswwebsite-9eb3-pr-1133.azurewebsites.net/events/clean-architecture-workshop)**

**Comment by johnxu16** [comment]
> See comments on the PR.

All comments has been dealt, please check newest changes.

And if you are ok with them, please approve this PR 🙂

**Review by danielmackay — APPROVED** [review]
Still not a fan of centring everything.  Besides that, it LGTM

**Pull request merged**
