### PR TITLE
💄Update body content style in events template

### LINKED ISSUE #1397: 💄 Events template - Body content style is bad
cc @danielmackay @Hona @wicksipedia 
**Is your feature request related to a problem? Please describe.**
image

As per my conversation with @jaydenalchin, he suggested some improvements to the events pages (e.g.
https://www.ssw.com.au/events/clean-architecture-superpowers-tour)

```[tasklist]
### Tasks
- [ ] Body content doesn't need to be in a card
- [ ] Make body content headings consistent with the rest of the page headings (centered)
- [ ] Make body content text consistent with the rest of the page
- [ ] Center images
- [ ] Make sure this looks good on all events pages
- [ ] Ensure these changes dont affect any other pages
- [ ] checked by @jaydenalchin
```

### PR DESCRIPTION
**Pull request by johnxu16**
As per @jaydenalchin and @bradystroud 's conversation, content style of events template needs to be updated.
1. Body content doesn't need to be in a card
2. Make body content headings consistent with the rest of the page headings (centered)
3. Make body content text consistent with the rest of the page
4. Center images
5. Make sure this looks good on all events pages
6. Ensure these changes dont affect any other pages

- Affected routes:  `/events/angular-superpowers-tour`

- Fixed #1397 

image
**Figure: https://app-sswwebsite-9eb3-pr-1434.azurewebsites.net/events/azure-superpowers-tour**

image
**Figure: https://app-sswwebsite-9eb3-pr-1434.azurewebsites.net/events/azure-superskills**

image
**Figure: https://app-sswwebsite-9eb3-pr-1434.azurewebsites.net/events/angular-superpowers-tour**

image
**Figure: https://app-sswwebsite-9eb3-pr-1434.azurewebsites.net/events/angular-workshop**

image
**Figure: https://app-sswwebsite-9eb3-pr-1434.azurewebsites.net/events/clean-architecture-superpowers-tour**

image
**Figure: https://app-sswwebsite-9eb3-pr-1434.azurewebsites.net/events/clean-architecture-workshop**

image
**Figure: https://app-sswwebsite-9eb3-pr-1434.azurewebsites.net/events/customized-courses**

image
**Figure: https://app-sswwebsite-9eb3-pr-1434.azurewebsites.net/events/net-superpowers-tour**

image
**Figure: https://app-sswwebsite-9eb3-pr-1434.azurewebsites.net/events/professional-tailored-scrum-training**

### CODE REVIEW

**Comment by jaydenalchin** [comment]
Hi @johnxu77 great stuff! 

Just one small bit of feedback:

1. Headings - should have _font-weight: 400_ to be consistent with the other H2s on the page

Thanks!

**Comment by bradystroud** [comment]
Hey @KristenHu 

1. Check this rule https://www.ssw.com.au/rules/write-a-good-pull-request/
2. Update this PR

**Comment by KristenHu** [comment]
> Hey @KristenHu
> 
> 1. Check this rule https://www.ssw.com.au/rules/write-a-good-pull-request/
> 2. Update this PR

Hey @bradystroud ,

Done😊

**Comment by KristenHu** [comment]
> Hi @johnxu77 great stuff!
> 
> Just one small bit of feedback:
> 
> 1. Headings - should have _font-weight: 400_ to be consistent with the other H2s on the page
> 
> Thanks!

Hey @jaydenalchin ,

**Done** - as per our conversation via Teams, all the font-weight of h2s has been changed to 500.😊

**Review by bradystroud — APPROVED** [review]
LGTM

**Pull request merged**
