### PR TITLE
💸 Megamenu - Refactor to Get Data From Tina

### LINKED ISSUE #1559: 💸 Megamenu - layout should be configurable in Tina
**Description**  
In order to get the new megamenu out sooner, we shipped a version with layout/routes hardcoded in a class.

See https://github.com/SSWConsulting/SSW.Website/blob/main/mock-data/mock-data.ts

**Proposed solution**  
Add a new object to store the layout, and configure it in Tina
That way, end users can make edits to the menu

```[tasklist]
### Tasks
- [x] Move menu to TinaCMS
- [ ] https://github.com/SSWConsulting/SSW.Website/issues/1848
- [x] Create Done video
```

### PR DESCRIPTION
**Pull request by Harry-Ross**
- Affected routes: `*`

- Fixed #1559

- [ ] If adding a new page, I have followed the [📃 New Webpage](https://github.com/SSWConsulting/SSW.Website/issues/new?assignees=&labels=&projects=&template=new_webpage.yml&title=%F0%9F%93%84+%7B%7B+TITLE+%7D%7D+) issue template

image
**Before**

image
**After**

**Done video:** https://www.youtube.com/watch?v=n1OB91ejNSo

### CODE REVIEW

**Review by amankumarrr — CHANGES_REQUESTED** [review]
Padding looks bit odd here
image

**Review by amankumarrr — COMMENTED** [review]
Products link seems to be broken 
image

**Review by amankumarrr — COMMENTED** [review]
It seems like we can't add a top level megamenu item 

To reproduce this:
 
1. Add Menu Groups 
2. Add Menu Columns

**Review by bradystroud — APPROVED** [review]
LGTM
Reviewed on a call with Harry and Aman

**Review by amankumarrr — APPROVED** [review]

**Pull request merged**
