### PR TITLE
✨ UG Embedded Live stream on home page

### LINKED ISSUE #189: ✨ UG Embedded Live stream on home page
As per my convesation with the TV team and Piers, the old website has an embedded live stream on the home page when the SSW TV channel is live (streamyard).

```[tasklist]
### Tasks
- [x] Get screenshots of the old website home page when we are live
![image](https://user-images.githubusercontent.com/16027480/219599959-90a3ec1d-29e9-4be2-918c-e33ebf4075e7.png)
**Figure: Sample live stream widget**
- [x] Fetch sharepoint event data from the old site. (Tech debt to be resolved in #51 )
- [x] Create a embed of the live stream to the home page - make this a component that can be added to other pages
```

### PR DESCRIPTION
**Pull request by jimmidier**
Closes #189 

- [x] Create a component for the embedded live stream widget
- [x] Fetch data from the old site
- [x] Overall UI
- [x] Thumbnail on scroll
- [x] Responsiveness
- [x] Support multiple speaker descriptions, both internal and external
- [x] Setup timer to update
- [x] Update live stream banner and widget to share timer and event info
- [x] Fix lint and scanning issues

image
**Figure: Sample widget, tested on system time 2023-02-15 07:00:00Z**

### CODE REVIEW

**Comment by wicksipedia** [comment]
What’s the url? When I click on the livestream banner I still get redirected to the old site

**Comment by jimmidier** [comment]
> What’s the url? When I click on the livestream banner I still get redirected to the old site

Creating Live UG page is not part of this PR. The PR only targets on the embedded live stream on the home page, and making it a reusable component that can be used on future pages including Live UG. Therefore the link of the banner stays the same.

To test it on home page you might need to change your system time to a point when there was an event airing. e.g. 2023-02-15 07:00:00Z

**Comment by jimmidier** [comment]
> What’s the url? When I click on the livestream banner I still get redirected to the old site

Creating Live UG page is not part of this PR. The PR only targets on the embedded live stream on the home page, and making it a reusable component that can be used on future pages including Live UG. Therefore the link of the banner stays the same.

To test it on home page you might need to change your system time to a point when there was an event airing. e.g. 2023-02-15 07:00:00Z

**Comment by jimmidier** [comment]
> What’s the url? When I click on the livestream banner I still get redirected to the old site

Creating Live UG page is not part of this PR. The PR only targets on the embedded live stream on the home page, and making it a reusable component that can be used on future pages including Live UG. Therefore the link of the banner stays the same.

To test it on home page you might need to change your system time to a point when there was an event airing. e.g. 2023-02-15 07:00:00Z

**Comment by wicksipedia** [comment]
We already have logic that lets us add a querystring param to test the live banner without changing system datetime. Can we do the same for this PR.

**Comment by jimmidier** [comment]
> We already have logic that lets us add a querystring param to test the live banner without changing system datetime. Can we do the same for this PR.

Technically we can. But in that case there won't be any content in the live stream except for the several buttons, if it's not during any live event at that time, so I wonder if if could be fully tested in this way. On the other hand the banner has its meaning, that notices the user for upcoming event, and is guaranteed to have meaningful countdowns even if the user forces it to show up using query param, whereas the live stream is only meant for streaming.

That said I can still add the logic if we decided to do so.

**Comment by jimmidier** [comment]
> We already have logic that lets us add a querystring param to test the live banner without changing system datetime. Can we do the same for this PR.

@wicksipedia  This is done.

image
**Figure: Showing banner and live stream using param strings. The youtube video and two blocks of descriptions might be empty if the fields from Sharepoint are not set yet**

**Comment by wicksipedia** [comment]
🐛 - unable to preview the changes, looks like a CORS issue

image

**Comment by jimmidier** [comment]
> 🐛 - unable to preview the changes, looks like a CORS issue

Done - This is fixed.

**Review by wicksipedia — APPROVED** [review]
I think the livestream component needs some refactoring but it'll be ok for now

**Pull request merged**
