### PR TITLE
Added extra security video to landing page + improved Benefits card 

### PR DESCRIPTION
**Pull request by tiagov8**
cc @matt-goldman 

Requested by @adamcogan : **Re: Enterprise IT Security Consulting and Auditing**

- Affected routes: https://www.ssw.com.au/consulting/security

### CODE REVIEW

**Comment by tiagov8** [comment]
**Note:** With the Benefits card change, the goal is to avoid this missalignment caused by inconsistent list in the content for the 1st card:

Screenshot 2024-03-11 at 3 07 46 PM

**Comment by matt-goldman** [comment]
@tiagov8 

Can we change:
> Azure AD B2C

to:
Microsoft Entra ID


image

**Comment by tiagov8** [comment]
> @tiagov8
> 
> Can we change:
> 
> > Azure AD B2C
> 
> to: Microsoft Entra ID
> 
> image

done

**Review by bradystroud — APPROVED** [review]
LGTM

**Review by matt-goldman — APPROVED** [review]
Hi @tiagov8 

Approved - although I note Adam's email says

> 1. Embed this video **before** mine 

So he may ask you to change it

**Comment by tiagov8** [comment]
> Hi @tiagov8
> 
> Approved - although I note Adam's email says
> 
> > 1. Embed this video **before** mine
> 
> So he may ask you to change it

Hi Matt, see the reasons I changed the position in the email: "**Re: Enterprise IT Security Consulting and Auditing**"

**Pull request merged**
