### PR TITLE
Consulting - Add tina consulting page

### LINKED ISSUE #2450: 📄 New consulting page for TinaCMS
### 1. People in the loop:

From @uly1 @UlyssesMaclaren 

### 2. Page template to copy:

https://www.ssw.com.au/consulting/mobile-application-development

### 3. CRM Record (only for consulting service pages):

https://ssw.crm6.dynamics.com/main.aspx?appid=05daa2a9-8768-446e-b9d3-580c8a6f9b8b&pagetype=entityrecord&etn=ssw_consultingservice&id=6487ac24-87f7-ee11-a1fe-00224812b9e4&lid=1712787040412

### 4. URI:

https://www.ssw.com.au/consulting/tinacms

### 5. Page Title:

Enterprise Development and Consulting for TinaCMS

### 6. Meta description:

Boost your website with TinaCMS consulting. Our experts provide personalized guidance for seamless content management integration.

### 7. Related URLs:

https://www.ssw.com.au/consulting/alm-tooling

### 8. Content:

**Want to build a TinaCMS website?**
Take advantage of the best fully open-source headless CMS for Git

**The benefits of TinaCMS**
TinaCMS revolutionizes collaboration between developers and content editors through its Git-based content management system, integrating content and code into a single source of truth. This setup enhances workflow efficiency, enabling direct content changes in the repository with robust version control and history tracking.

Enhancing the user experience, TinaCMS offers a real-time visual editing feature, allowing for intuitive content creation and management directly within the website or app interface. Customizable content blocks and a real-time preview function ensure high-quality content publication. Emphasizing user control and scalability, TinaCMS is open-source and optionally self-hosted, designed to maintain optimal performance and flexibility for projects of any size, making content as manageable as if it were in a database.

Video: https://www.youtube.com/watch?v=zRkeKSZjlyw

Tina is an open-source, Git-backed headless content management system (CMS) that empowers both developers and content creators to collaborate seamlessly on a single platform. Tina enables developers to craft a custom visual editing experience perfectly tailored to their website or application while supporting a broad range of content types such as Markdown, MDX, and JSON.

**Own Your Content**
Don't lock your content in a 3rd-party service. Tina writes to files in your repository (MDX, Markdown, JSON, etc)

**An API for your Content**
Easily fetch your file-based content using Tina's Data Layer

**Configure with Code**
Tina is code-first and fully typed. Define your CMS in the Tina config file in your repository

**Merge With Confidence**
Tina Cloud Enterprise customers can review, approve, and manage content on different branches

**Unbeatable UX**
Editing content in Markdown, MDX, and JSON files doesn't need to feel clunky. Tina supports a live preview that takes the UX to the next level

**Composable Blocks**
Create reusable components that you can edit with Tina. Let your team assemble pages like a site-builder.

Technologies:

GitHub 
Responsive sites

### PR DESCRIPTION
**Pull request by wicksipedia**
Adds TinaCMS consulting page and link to the consulting list page

- Affected routes:
  `/consulting`
  `/consulting/tinacms`

- Fixed #2450

- [x] If adding a new page, I have followed the [📃 New Webpage](https://github.com/SSWConsulting/SSW.Website/issues/new?assignees=&labels=&projects=&template=new_webpage.yml&title=%F0%9F%93%84+%7B%7B+TITLE+%7D%7D+) issue template

- [x] Include done video or screenshots

CleanShot 2024-04-16 at 10 15 43

CleanShot 2024-04-16 at 10 16 46

### CODE REVIEW

**Review by uly1 — APPROVED** [review]

**Review by camillars — APPROVED** [review]

**Comment by tiagov8** [comment]
Hi @wicksipedia 

The logo on the index page is missing a breathing space + seems cut... see how all the others have a padding so they look small.

- [x] 1. Please replace with this one

tina-logo

**Review by tiagov8 — CHANGES_REQUESTED** [review]
- [ ] Action https://github.com/SSWConsulting/SSW.Website/pull/2478#issuecomment-2058025619

**Review by uly1 — APPROVED** [review]

**Review by tiagov8 — APPROVED** [review]
Hi @wicksipedia 

Approved, but I noticed something that might be unrelated.

If you look at the cards... most will have **logo + text**... 
But the "Responsive Website" has **logo + heading + text**

I think we should remove the heading from it and others that might have it. Agree?

**Comment by wicksipedia** [comment]
> Hi @wicksipedia
> 
> Approved, but I noticed something that might be unrelated.
> 
> If you look at the cards... most will have **logo + text**... But the "Responsive Website" has **logo + heading + text**
> 
> I think we should remove the heading from it and others that might have it. Agree?

This would most probably make other pages go out of whack on other pages.

It would make more sense to be consistent with tech cards as a whole. Either make heading mandatory or drop it altogether.

Can you raise it as another PBI pls

**Comment by tiagov8** [comment]
> Can you raise it as another PBI pls

Done - https://github.com/SSWConsulting/SSW.Website/issues/2481

**Pull request merged**
