### PR TITLE
⚠️ Do Not Merge fix console.log on production

### LINKED ISSUE #1164: 🚑 console.log on production
Description:
1. https://www.ssw.com.au/consulting
2. Open devtools
3. Consulting data requested with graphql is printed on console panel

Image:
Image
**Figure: data printed on console panel**

### PR DESCRIPTION
**Pull request by johnxu16**
Fixes #1164 

Affected routes:

- /consulting

Add done video, screenshots

image
**Figure: Empty console panel**

### CODE REVIEW

**Review by bradystroud — CHANGES_REQUESTED** [review]
Hey @johnxu77 
As discussed with Aman, I think we should be able to see the logs on our PR builds.

**Comment by bradystroud** [comment]
1 week old - what is the status of this one @johnxu77 ?

**Comment by johnxu16** [comment]
> 1 week old - what is the status of this one @johnxu77 ?

For differentiating staging env and production env, I set up a new environment variable BUILD_TAG on template_build

**Comment by johnxu16** [comment]
As per conversation with Matt W, we should avoid changing template-build as possible as we can.

- [ ] Changing bicep file using in creating azure resource group

**Pull request closed without merging**
