### PR TITLE
Update events page banner

### PR DESCRIPTION
**Pull request by hveraus**
- Affected routes: 
- https://www.ssw.com.au/events/clean-architecture-superpowers-tour
- https://www.ssw.com.au/events/ai-workshop
- https://www.ssw.com.au/events/angular-workshop

- [ ] Update events logo on the banner area

### CODE REVIEW

**Review by johnxu16 — APPROVED** [review]

**Comment by wicksipedia** [comment]
Hey @hveraus,

I can't see any of the old or new images in the PR.

Is this expected?

Can they be included in the PR pls

CleanShot 2024-04-19 at 11 25 12

**Comment by tiagov8** [comment]
cc @johnxu16 

Hey @hveraus 

As per @wicksipedia , we can see the images names changed but we cannot see the new images... 

- [ ] 1. Can you make sure to upload the new images with these changes?
OR paste a link to another PR with the uploads if that is the case

**Review by tiagov8 — CHANGES_REQUESTED** [review]
cc @johnxu16 

Hey @hveraus 

As per @wicksipedia , we can see the images names changed but we cannot see the new images... 

- [x] 1. Can you make sure to upload the new images with these changes?
OR paste a link to another PR with the uploads if that is the case

**Comment by hveraus** [comment]
> cc @johnxu16
> 
> Hey @hveraus
> 
> As per @wicksipedia , we can see the images names changed but we cannot see the new images...
> 
> * [x]  1. Can you make sure to upload the new images with these changes?
>   OR paste a link to another PR with the uploads if that is the case

Hi Tiago, I have upload those images again in Github, should be OK now for this PR.
But I am no 100% sure why the images did not come through when I upload them from Tina media manager. 
It happens few times now, not not happen every time when I tried to upload images from Tina.

**Comment by hveraus** [comment]
@tiagov8 

1. please review the change you requested.

**Review by tiagov8 — APPROVED** [review]

**Pull request merged**
