### PR TITLE
Company - Adding index page template

### LINKED ISSUE #1020: ✨ Page - Company index
https://www.ssw.com.au/ssw/Company/Default.aspx

```[tasklist]
### Tasks
- [x] Create a collection for this page
- [x] Create the template
- [x] Add visual editing
- [x] Get it approved from designer
- [x] Update Mega menu link
- [x] Add Front Door redirect
```

### PR DESCRIPTION
**Pull request by amankumarrr**
Related #1020 
Affected routes:

- `/company`  -->

Add done video, screenshots

image

**Figure: Company Index page - v2** 

image

**Figure: Mobile view - Company Index page - v2** 

image
image

**Figure: Company Index page**

### CODE REVIEW

**Review by jaydenalchin — CHANGES_REQUESTED** [review]
1. Page banner - Remove duplicate logo, instead implement as a background image behind a page title (h1) e.g. "Company Index".
2. Card titles - These h2's should have the same text styling as h2's on the homepage (but red)
3. Cards - The card padding looks off and the cards should be more responsive. Looks like they're all a static size despite longer and shorter content. "Our People" card contains lots of text that breaks bounding box. I'd recommend removing the margin-top from description text and doubling the x padding for these cards (py-4 px-8) to make content feel centred. Cards should grow to the size of the largest card in their row. 
4. Content - Typo under Our Offices. Change from **workd** to **world.** including the full stop.

image
**Figure: Showing h2 styling + responsive needs in browser tools** 

image
**Figure: Card padding recommendation**

**Review by jaydenalchin — APPROVED** [review]
LGTM 🚀

**Review by bradystroud — CHANGES_REQUESTED** [review]
1 minor change - make the heading margin consistent

image

**Review by bradystroud — APPROVED** [review]
LGTM

Changes I requested were already actioned, just waiting for the deployment

**Pull request merged**
